name: Makefile CI

on:
  push:
    branches: ["branchMake"]
  pull_request:
    branches: ["branchMake"]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Chekout code
        uses: actions/checkout@v2

      - name: Install build tools
        run: sudo apt-get install -y build-essential

      - name: Build
        run: make

      - name: Run the executable
        run: ./program
