name: Tests

on: 
  push:
    branches: ["branchAutoTest"]
  pull_request: 
    branches: ["branchAutoTest"]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt get update
          sudo apt get install -y build-essential libgtest-dev cmake

      - name: Build
        run: |
          aclocal
          autoconf
          automake --add-missing
          ./configure
          cmake
          make

      - name: Tests
        run: ./tests/test
